fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

leave:
    resource: "@LeaveBundle/Resources/config/routing.yml"
    prefix: /