fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

author:
    resource: "@AuthorBundle/Resources/config/routing.yml"
    prefix: /

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix: /