security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            encode_as_base64: false
            iterations: 4

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        api_key_user_provider:
            id: AppBundle\Security\ApiKeyUserProvider
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern: ^/users/
            anonymous: true
            stateless: true
            logout: true

        api:
            pattern: ^/
            anonymous: false
            stateless: true
            simple_preauth:
                authenticator: AppBundle\Security\ApiKeyAuthenticator
                provider: api_key_user_provider
            http_basic:
                provider: fos_userbundle