UserBundle\Entity\User:
    type: entity
    repositoryClass: UserBundle\Entity\Repository\UserRepository
    table: compiereUser
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        apiKeys:
            targetEntity: UserBundle\Entity\ApiKey
            mappedBy: user
            cascade: ["all"]